### ISSUE TITLE
Add num_streams to status JSON so I don't have to count them in the app

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#10]
I can count the ch<n>_ keys in the status array, but it'd be easier if I didn't have to.

Have /status also contain a num_channels property. 2 would mean channels [0..1]

**Comment by johncclayton** [comment]
What does num_streams give you? What is it actually?

**Comment by johncclayton** [comment]
Oh, you mean the number of actual channels the charger can support?

**Comment by scornflake** [comment]
Yup

**Comment by scornflake** [comment]
So then I can run off and create various Observables for various channel URLs, and let rxjs worry about merging all that together. Nice.

**Comment by johncclayton** [comment]
Ok, I'll hard code it to 2 then?  Are there other chargers that have only a single channel?

**Comment by johncclayton** [comment]
I say that because all the Duo style chargers have two channels.  The 308B has one, but its a serial protocol and I don't have code to read that one and don't plan to either at this point.
