### ISSUE TITLE
minor: iCharger 406 Duo device ID confirmed (not a bug)

### ISSUE THREAD

**Issue by raplin** [johncclayton/electric#122]
Hi, comment on this line says the ID number is a TODO

https://github.com/johncclayton/electric/blob/c41f58352497d8ba085ec427532e90a5e7723b23/src/server/electric/models.py#L78

I have an iCharger 406Duo and the ID number is correct, 67. 
Works fine. Thanks, awesome project.

**Comment by scornflake** [comment]
:-)  only took me most of a year to reply! 

Thanks. I've removed the comment.
