### ISSUE TITLE
curr_out_power appears to be off by factor of 10 (on iCharger 406Duo)

### ISSUE THREAD

**Issue by raplin** [johncclayton/electric#123]
https://github.com/johncclayton/electric/blob/c41f58352497d8ba085ec427532e90a5e7723b23/src/server/electric/models.py#L356
On my iCharger 406Duo I believe this value reads 10 times too small. Suggest change to /100 (from /1000) if you can repeat the issue.

My iCharger reports " 'software_ver': 2107" over modbus

**Comment by scornflake** [comment]
Yep, appears to be same here. I'll adjust. I don't actually thing we use this in the UI yet.
