### ISSUE TITLE
Does this do any logging?

### ISSUE THREAD

**Issue by virtual812** [johncclayton/electric#125]
Not sure creating an issue is the best way to ask this, but i so no other way.

I have a 308Duo that for some reason says "SD error!" when attempting to send log data to a PC.
I've ruled out the SD card itself as the issue, the issue is definitely in the charger.

I've been able to continue logging by doing it in real time connected to a PC, but if this system with the raspi can also cover the logging needs then it would be a no brainer to go with this.

So.... does this do logging?

Typically looking to do a 3 cycle charge>discharge>store to characterize battery packs.

**Comment by scornflake** [comment]
At the moment, no. It'd certainly be capable, but that'd require more work on the server that we started out to do.  We havn't ruled it out, it's more of a "if someone puts their hand up to implement it, yay" thing.
