### ISSUE TITLE
Image?

### ISSUE THREAD

**Issue by Marantzi** [johncclayton/electric#128]
Hi, 
in the dropbox there are two different images:
1) electric-sd-card_feature_rpi3bx_625.img
2) electric-sd-card_master_592.img

What's the difference, and which one I should use with Pi3b (guess the 1st one?). What is the other .img for in Electric project, please?

Another question: is it still so that 3b PLUS is not supported / functioning?

Thanks a lot for a great project!

**Comment by scornflake** [comment]
electric-sd-card_master_592.img for now.  from memory.
The 3bx is experimental and not working.
