### ISSUE TITLE
What is the ssh/console login for the electric pi image?

### ISSUE THREAD

**Issue by pvogel1967** [johncclayton/electric#129]
Subject says it all -- I'm successfully connecting via the app, etc. but you have upgrade instructions, etc. that assume the user can ssh to the pi, but I cannot find anywhere that you discuss the credentials for that ssh.  Also, the only place I've found where you disclose the network password for the "Electric" wifi is in your video -- I shouldn't have to watch the video to get connected!

**Comment by pH7-JP1** [comment]
Userid pirate and password hypriot
