### ISSUE TITLE
I think the server may be barfing after quite some time

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#13]
Exception AttributeError: "'iChargerMaster' object has no attribute '_is_opened'" in <bound method iChargerMaster.__del__ of <electric.icharger.modbus_usb.iChargerMaster object at 0x6cdcabd0>> ignored

It seems to stop the server

**Comment by johncclayton** [comment]
Need to get more details as to the context, I've seen this to and this
error is *definately* a problem with modbus_tk using the .close() method
within the __del__ - whereby apparently there are no guarantees that the
instance vars are still around within __del__, so bad stuff happens - e.g.
NOT best practise.

Thanks,
--
John Clayton
Skype: johncclayton

**Comment by johncclayton** [comment]
Again, based on todays work/testing I think this issue is no longer relevant.
