### ISSUE TITLE
IR values, divide by 10 to get mOhms

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#14]
In the interest of client laziness, 

           "balance": 0, 
            "cell": "0", 
            "ir": 97, 
            "v": 3.825

Shows on the charger as 9.7mOhms. Divide at the server to give mOhms over the wire.

**Comment by scornflake** [comment]
Same is true for:
line_intern_resistance

**Comment by johncclayton** [comment]
and cell_total_ir I presume, but since that's always been 0 no idea.

**Comment by johncclayton** [comment]
fixed.
