### ISSUE TITLE
After completing 'event' (charge/stop/discharge), hh:mm still non-zero

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#27]
Finished a discharge.
'timestamp' is still non-zero.

![icharger_308_duo](https://cloud.githubusercontent.com/assets/1758762/21748263/96fa95bc-d5e5-11e6-9090-2c664e1a55e7.png)

Here's the json AFTER the discharge:
{
    "battery_leads_plugged_in": true, 
    "battery_plugged_in": true, 
    "cell_count_with_voltage_values": 6, 
    "cell_total_ir": 23.9, 
    "cell_total_voltage": 17.418000000000003, 
    "cells": [
        {
            "balance": 0, 
            "cell": 0, 
            "ir": 5.6, 
            "v": 3.842
        }, 
        {
            "balance": 0, 
            "cell": 1, 
            "ir": 5.7, 
            "v": 3.843
        }, 
        {
            "balance": 0, 
            "cell": 2, 
            "ir": 7.0, 
            "v": 3.842
        }, 
        {
            "balance": 0, 
            "cell": 3, 
            "ir": 5.6, 
            "v": 3.843
        }, 
        {
            "balance": 0, 
            "cell": 4, 
            "ir": 0.0, 
            "v": 0.0
        }, 
        {
            "balance": 0, 
            "cell": 5, 
            "ir": 0.0, 
            "v": 0.0
        }, 
        {
            "balance": 0, 
            "cell": 6, 
            "ir": 0.0, 
            "v": 0.0
        }, 
        {
            "balance": 0, 
            "cell": 7, 
            "ir": 0.0, 
            "v": 0.0
        }, 
        {
            "balance": 0, 
            "cell": 8, 
            "ir": 102.4, 
            "v": 1.024
        }, 
        {
            "balance": 4, 
            "cell": 9, 
            "ir": 102.4, 
            "v": 1.024
        }
    ], 
    "channel": 0, 
    "charger_presence": "connected", 
    "control_status": 0, 
    "curr_ext_temp": 23.1, 
    "curr_inp_volts": 23.757, 
    "curr_int_temp": 39.4, 
    "curr_out_amps": 0.0, 
    "curr_out_capacity": 0, 
    "curr_out_power": 0.0, 
    "curr_out_volts": 15.377, 
    "cycle_count": 0, 
    "dlg_box_id": 0, 
    "line_intern_resistance": 26.5, 
    "run_error": 0, 
    "run_status": 0, 
    "timestamp": 1168.0
}

**Comment by johncclayton** [comment]
Yes - the iCharger does leave some state in the buffers once charging completes.  I would prefer the server can detect this and blank things out.
