### ISSUE TITLE
Figure out how to identify the device_id in the server, and NOT use global state

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#44]
Hmmm...
some kind of HTTP / Flask state store we can use?

**Comment by johncclayton** [comment]
You mean not use evil_global to store the device_id?  But but but... I LOVE GLOBALS man... its a throw-back to the ... 1700's!

**Comment by scornflake** [comment]
I think this is done as a result of the zmq work?  Please close if you agree.

**Comment by johncclayton** [comment]
NFI
