### ISSUE TITLE
Consider disabling HDMI to consume less power on Pi3

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#48]
Use this command to turn it off: /opt/vc/bin/tvservice -o And this command to turn it on: /opt/vc/bin/tvservice -p I googled "raspberry pi 3 turn off hdmi" and found this page:

Primarily for USB based UPS / rechargeable situation (for clean shutdown).

**Comment by johncclayton** [comment]
How about I give you a RESTful end point to do that?

**Comment by scornflake** [comment]
Yep, make this lowest of lowest priority tho...

—
Neil Clayton
neil@cloudnine.net.nz

**Comment by scornflake** [comment]
tempted to close this off, because, who cares?

**Comment by johncclayton** [comment]
who cares
