### ISSUE TITLE
Saving presets doesn't work

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#60]
Tried to save a preset, it failed.
It also left the app in a broken state after the "error toast" was dismissed.

It seems the URL wasn't found.
Which is odd, because it IS there. I had this same problem with /store/ as well, until I renamed it, restarted the server, then RENAMED IT BACK. Ultra weird.  The code IS there. Flask being weird?

![img_3572](https://cloud.githubusercontent.com/assets/1758762/26769950/0aae0698-4a07-11e7-9929-90c973204b10.PNG)

**Comment by johncclayton** [comment]
Nah - it does apparently.  Just ignore the is_fixed flag and tadaaaa... saving works.  So I think we'll just leave it at that.
