### ISSUE TITLE
Totals are not correct when using multiple channels

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#63]
![screen_shot_2017-06-06_at_6_12_04_pm](https://cloud.githubusercontent.com/assets/1758762/26816039/ca76af16-4ae3-11e7-81f8-a01f587635bb.png)

**Comment by scornflake** [comment]
again, I can't help but wonder if redux would help. 
Mainly because the way the component gets it's data right now is kinda suck. It's getting hold of a subscription, and using the observable directly.

I *could* modify it, and maybe I will... maybe I'll use channel state as a way to introduce/try redux.

**Comment by johncclayton** [comment]
reeeeddddduuuuuuux
