### ISSUE TITLE
It's very very easy to get the charger confused (potential killer)

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#64]
This is pretty serious.

It's almost impossible to kick off a charge on both channels at the moment.
Something is causing "weirdness/corruption".  The charger shows a "error 3500 - the other channel is occupied"

See vid(s)

https://www.dropbox.com/s/jmacoyfjr1yj6wu/IMG_3573.MOV?dl=0

and

https://www.dropbox.com/s/3o0d3xf3yr3vxpd/IMG_3574.MOV?dl=0

and showing the charger in a dead state:

https://www.dropbox.com/s/ztbrmp3qbvgmrcg/IMG_3576.MOV?dl=0

about the only thing I can think of is that the UI is sending stuff for ch#1, that's interfering with me starting something on ch#2.  But I killed the flask process on the pi3, so that there was NO chance of it trying to talk to the charger, and the same as last video still results (charger borked).

I even unplugged all packs from the charger. It STILL does the same thing (error 3500). 
Removing the pack from ch#2, shifting it to ch#1, and beginning a charge there... works, but the error STILL comes up on ch#2.  Pretty f*ked imho.

So:

1) how did I get it into this state?
2) how do we prevent it?

**Comment by johncclayton** [comment]
Based on todays testing - I believe this is now fixed.
