### ISSUE TITLE
Flask server does not allow client to retry, after error condition (timeout)

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#78]
Dear server side people, please do this:

1. With everything is running, stop zmq.
2. The client will die within 10s, and show an error (so will flask).
3. Restart ZMQ.
4. The HTTP (flask) server continues to hang and not accept/process requests.

**Comment by johncclayton** [comment]
Reduced timeout to 5s, and on failure the zmq_marshall layer will reset its connection, works a lot better - not sure its 100% though as the prior HTTP requests still fail, but retry those and they then succeed.

**Comment by johncclayton** [comment]
for Neil to test on his side.

**Comment by scornflake** [comment]
seems happy now
