### ISSUE TITLE
Check if we need WKWebView for iOS app (do we need the performance)?

### ISSUE THREAD

**Issue by scornflake** [johncclayton/electric#81]
We need to run some rudimentary performance checks on the UI, and see whether we really need WKWebView - IF we do then it's CORS handling is gonna be problematic.

Probably a CORS issue and doomed for failure of all time.
This would mean a need to use HTTPS to the REST server. Fine, except you cannot use self signed certs ...

So.
Yay.

**Comment by johncclayton** [comment]
I think we got around this using a special API call that had to be bundled into Cordova - possible but from memory a royal pain.
